### ISSUE TITLE
Twig removed MacroAutoImportNodeVisitor

### ISSUE THREAD

**Issue by vukbgit** [JBlond/twig-trans#9]
Hello, Twig v3.15.0 removed MacroAutoImportNodeVisitor (see [changelog](https://github.com/twigphp/Twig/blob/3.x/CHANGELOG)) and so broke twig-trans v1.1.0 in:

jblond/twig-trans/src/jblond/TwigTrans/Translation.php::108

with error

Class "Twig\NodeVisitor\MacroAutoImportNodeVisitor" not found

**Comment by JBlond** [comment]
Thank you for your report @vukbgit ! Closed in https://github.com/JBlond/twig-trans/pull/10

**Comment by vukbgit** [comment]
fast and furious!

thank you very much, bye
